model:
  encoder:
    encoder_type: mamba
    encoder:
      mamba:
        d_input: 3
        d_output: 128
        d_model: 128
        n_layer: 4
        bidirectional: true
    use_quantizer: true
    quantizer_type: fsq
    quantizer:
      fsq:
        levels: [4, 4, 4, 4, 4, 4]
        d_input: ${model.encoder.encoder.mamba.d_output}
  decoder:
    decoder_type: mamba
    decoder:
      mamba:
        d_input: ${model.encoder.encoder.mamba.d_output}
        d_output: 3
        d_model: 128
        n_layer: 6
        bidirectional: true
  registration:
    all_atom_coords:
      pc_1: decoding
      pc_2: structure
      mask: structure_known_all_atom_mask
    bb_atom_coords:
      pc_1: decoding
      pc_2: structure
      mask: bb_atom_known_structure_mask
    sc_atom_coords:
      pc_1: decoding
      pc_2: structure
      mask: sc_atom_known_structure_mask
  losses:
    loss:
      structure_rmsd:
        loss_type: rmsd
        prediction_name: all_atom_coords
        target_name: structure
        mask_name: structure_known_all_atom_mask
        weight: 1
        root: true
      distance_inter_atom_intra_residue:
        loss_type: inter_atom_distance
        prediction_name: all_atom_coords
        target_name: structure
        mask_name: structure_known_all_atom_mask
        res_idx_name: residue_ids
        weight: 1
        root: true
    monitor:
      structure_rmsd_bb:
        loss_type: rmsd
        prediction_name: bb_atom_coords
        target_name: structure
        mask_name: bb_atom_known_structure_mask
        root: true
      structure_rmsd_sc:
        loss_type: rmsd
        prediction_name: sc_atom_coords
        target_name: structure
        mask_name: sc_atom_known_structure_mask
        root: true
      structure_tm_cref:
        loss_type: tm
        prediction_name: bb_atom_coords
        target_name: structure
        mask_name: cref_atom_known_structure_mask
        seq_type: protein